org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=.tools/jdk17/jdk-17.0.18+8

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.18
forge_version_range=[47.4.18,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=easyadventure
mod_name=Easy Adventure
mod_license=All Rights Reserved
mod_version=1.6.1
mod_group_id=com.eddy1.easyadventure
mod_authors=EdDYON
mod_description=Pack your base, carry it anywhere, and deploy it back with one key. Compatible with Forge 1.20.1.
