modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="easyadventure"
version="1.6.1"
displayName="Easy Adventure"
authors="EdDYON"
logoFile="logo.png"

description='''
Pack your base, carry it anywhere, and deploy it back with one key.
Compatible with NeoForge 1.21.1.
'''

[[dependencies.easyadventure]]
modId="neoforge"
type="required"
versionRange="[21.1.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.easyadventure]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
